### ISSUE TITLE
Collect function for Gauge not functionnal

### ISSUE THREAD

**Issue by cyberbobjr** [willsoto/nestjs-prometheus#1225] opened 2022-01-14 15:12 UTC
Hi,

I'm trying to use the collect function for the Gauge metric, but this function is not functional for getting data inside a service.

The workaround is really bad because i use a global variable, and i instantiate the metric with Gauge class from "prom-client" :

```
import {Gauge} from 'prom-client';

@Injectable()
export class UpdateAssetImageService {
    private gauge;

    constructor() {
        this.gauge = new Gauge({
            name: "asset_image_generated",
            help: "metric_help",
            collect() {
                this.set(counter);
            }
        })
    }

```

and "counter" is a global variable.

How can i use the collect from module please ?

**Comment by willsoto** [comment] 2022-01-14 17:33
Can you post a minimal reproduction please?

**Comment by willsoto** [comment] 2022-03-15 15:49
Since I haven't gotten a reply, I am closing. Feel free to re-open with a minimal reproduction

**Closed by willsoto** 2022-03-15 15:49 UTC
Labels: question, waiting
